<a href="https://colab.research.google.com/github/physicaone/loss_IG/blob/master/%5B210603%5Dget_statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
try:
    from google.colab import drive
    drive.mount('/content/drive')
    base='drive/MyDrive'
except:
    base='Google Drive'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import pandas as pd
import numpy as np

In [3]:
n_hid_list=[1,2,4,8]
T='3.2'

In [10]:
S=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_T={T}_S.pkl'.format(base=base, T=T))
for n_hid in n_hid_list:
    bias_2nd_cumulant1=0; bias_2nd_cumulant2=0
    FE=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE.pkl'.format(base=base, n_hid=n_hid, T=T))
    FE_V=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE_V.pkl'.format(base=base, n_hid=n_hid, T=T))
    bias_CM=-S['CM']-FE['CM']+FE_V['CM']
    for m in range(10):
        bias_CM_m=-S['CM_m'][str(m)]-FE['CM_m'][str(m)]+FE_V['CM_m'][str(m)]
        for n in range(10):
            bias_tmp_mn=-S['CM']-FE['mn'][str(m)][str(n)]+FE_V['mn'][str(m)][str(n)]
            bias_2nd_cumulant1+=(bias_CM-bias_tmp_mn)**2 
            bias_2nd_cumulant2+=(bias_CM_m-bias_tmp_mn)**2
    print('n_hid:{n_hid}, cumulant1:{c1}, cumulatn2:{c2}'.format(n_hid=n_hid, c1=bias_2nd_cumulant1/100, c2=bias_2nd_cumulant2/100))

n_hid:1, cumulant1:0.007264962795051064, cumulatn2:0.01685438262676552
n_hid:2, cumulant1:0.039276016874621365, cumulatn2:0.13473173474864997
n_hid:4, cumulant1:1.0092512271802934, cumulatn2:2.474451161424211
n_hid:8, cumulant1:0.2731328603849761, cumulatn2:0.4227827138263445

In [13]:
S=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_T={T}_S.pkl'.format(base=base, T=T))
for n_hid in n_hid_list:
    FE=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE.pkl'.format(base=base, n_hid=n_hid, T=T))
    FE_V=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE_V.pkl'.format(base=base, n_hid=n_hid, T=T))
    list_CM=[]; list_CM_m_std=[]
    for m in range(10):
        list_CM_m=[]
        for n in range(10):
            bias_mn=-S['CM']-FE['mn'][str(m)][str(n)]+FE_V['mn'][str(m)][str(n)]
            list_CM.append(bias_mn); list_CM_m.append(bias_mn)
        list_CM_m_std.append(np.std(list_CM_m))
    print('n_hid={n_hid}, std_variance1={c1}, std_variance2={c2}'.format(n_hid=n_hid, c1=np.std(list_CM), c2=np.mean(list_CM_m_std)))

n_hid=1, std_variance1=0.08359587598221822, std_variance2=0.07506435325915026
n_hid=2, std_variance1=0.1446492355434823, std_variance2=0.0862007272204811
n_hid=4, std_variance1=0.05243977551479597, std_variance2=0.04258915524699485
n_hid=8, std_variance1=0.03209838437555174, std_variance2=0.027780137917635433

In [20]:
for n_hid in n_hid_list:
    variance1=0; variance2=0
    dE=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_dE.pkl'.format(base=base, n_hid=n_hid, T=T))
    FE=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE.pkl'.format(base=base, n_hid=n_hid, T=T))
    for m in range(10):
        for n in range(10):
            variance1=+dE['CM'][str(m)][str(n)]-FE['mn'][str(m)][str(n)]+FE['CM']
            variance2=+dE['CM_m'][str(m)][str(n)]-FE['mn'][str(m)][str(n)]+FE['CM_m'][str(m)]
    print(n_hid, variance1/100, variance2/100)

1 -0.0008994445172548282 -0.0005431773042202082
2 0.0012724101989149972 -0.0007451783732771844
4 0.00900750693714052 0.0033369085158397025
8 0.05545489090832099 0.054347723777850694

In [15]:
dict0={}
for m in range(10):
    dict0[str(m)]=[]
    for n in range(10):
        value=[]
        for n_hid in [1,2,4,8]:
            FE=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE.pkl'.format(base=base, n_hid=n_hid, T=T))
            FE_V=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE_V.pkl'.format(base=base, n_hid=n_hid, T=T))
            S=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_T={T}_S.pkl'.format(base=base, T=T))
            value.append(np.round(-S['CM_m'][str(m)]-FE['mn'][str(m)][str(n)]+FE_V['mn'][str(m)][str(n)],3))
        dict0[str(m)].append(value)
df = pd.DataFrame(data=dict0)

df
# Bias
# column index:m, row index:n, 1칸에 n_hid=1,2,4,8순서대로 값 기입

                               0  ...                             9
0     [0.374, 0.1, 0.045, 0.013]  ...  [0.445, 0.137, 0.074, 0.028]
1     [0.44, 0.108, 0.02, 0.048]  ...  [0.393, 0.164, 0.019, 0.045]
2   [0.378, 0.135, 0.08, -0.004]  ...  [0.299, 0.157, 0.032, 0.037]
3   [0.334, 0.141, 0.045, 0.035]  ...  [0.426, 0.138, 0.056, 0.029]
4    [0.48, 0.139, 0.048, 0.025]  ...   [0.469, 0.124, 0.037, 0.01]
5  [0.599, 0.107, 0.115, -0.008]  ...  [0.418, 0.112, 0.051, 0.008]
6   [0.55, 0.109, 0.038, -0.091]  ...   [0.42, 0.099, 0.003, 0.024]
7    [0.473, 0.16, 0.054, 0.011]  ...   [0.479, 0.131, 0.03, 0.019]
8   [0.309, 0.106, 0.052, 0.012]  ...   [0.38, 0.169, 0.041, 0.018]
9    [0.392, 0.092, 0.09, 0.005]  ...  [0.335, 0.154, 0.037, 0.011]

[10 rows x 10 columns]

In [16]:
dict_CM_m={}; dict_CM={}
for m in range(10):
    dict_CM_m[str(m)]=[]
    dict_CM[str(m)]=[]
    for n in range(10):
        value1=[]; value2=[]
        for n_hid in [1,2,4,8]:
            FE=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_FE.pkl'.format(base=base, n_hid=n_hid, T=T))
            dE=pd.read_pickle('{base}/loss_IG/3*3/data/3*3_PT20_0.1M_n_hid={n_hid}_T={T}_dE.pkl'.format(base=base, n_hid=n_hid, T=T))
            value1.append(np.round(dE['CM_m'][str(m)][str(n)]-FE['mn'][str(m)][str(n)]+FE['CM_m'][str(m)],3))
            value2.append(np.round(dE['CM'][str(m)][str(n)]-FE['mn'][str(m)][str(n)]+FE['CM'],3))
        dict_CM_m[str(m)].append(value1)
        dict_CM[str(m)].append(value2)
df_CM = pd.DataFrame(data=dict_CM); df_CM_m = pd.DataFrame(data=dict_CM_m)

In [22]:
df_CM

                               0  ...                              9
0   [-0.091, 0.107, 0.97, 5.665]  ...   [0.035, 0.134, 0.987, 5.977]
1  [-0.109, 0.182, 0.947, 5.744]  ...  [-0.096, 0.133, 0.937, 5.608]
2   [-0.092, 0.11, 1.014, 5.303]  ...   [-0.112, 0.155, 0.897, 5.48]
3  [20.807, 0.138, 0.967, 7.862]  ...  [-0.018, 0.225, 0.952, 6.004]
4  [-0.027, 0.107, 0.955, 7.763]  ...   [-0.024, 0.21, 0.878, 7.845]
5   [0.115, 0.096, 3.523, 2.146]  ...    [-0.088, 0.2, 7.583, 2.299]
6   [0.009, 0.188, 0.932, 5.059]  ...  [-0.024, 0.112, 3.559, 7.847]
7    [0.009, 0.141, 0.989, 2.36]  ...  [-0.069, 0.214, 0.906, 6.119]
8   [-0.16, 0.179, 3.634, 4.695]  ...   [-0.026, 0.15, 1.065, 2.257]
9   [-0.05, 0.169, 1.006, 2.367]  ...   [-0.09, 0.127, 0.901, 5.545]

[10 rows x 10 columns]

In [18]:
df_CM_m

                              0  ...                               9
0  [0.081, 0.186, 0.663, 6.063]  ...     [0.069, -0.076, 0.39, 5.37]
1   [0.076, 0.23, 0.623, 4.719]  ...  [-0.053, -0.082, 0.339, 4.956]
2   [0.081, 0.193, 0.712, 5.68]  ...  [-0.078, -0.072, 0.311, 5.002]
3  [19.21, 0.209, 0.655, 8.375]  ...   [0.019, -0.029, 0.347, 6.541]
4    [0.151, 0.196, 0.646, 7.7]  ...    [0.02, -0.024, 0.316, 8.088]
5  [0.291, 0.174, 3.854, 1.379]  ...  [-0.044, -0.051, 7.141, 1.659]
6  [0.194, 0.237, 0.618, 4.245]  ...   [0.012, -0.118, 5.594, 7.167]
7  [0.181, 0.227, 0.671, 1.308]  ...   [-0.02, -0.039, 0.304, 5.269]
8  [0.014, 0.229, 3.949, 3.448]  ...   [0.007, -0.062, 0.423, 2.075]
9  [0.119, 0.211, 0.699, 1.671]  ...  [-0.054, -0.075, 0.334, 5.435]

[10 rows x 10 columns]